dist: xenial
language: java

jdk:
  - openjdk12

branches:
  only:
  - staging

addons:
  sonarcloud:
    organization: "ariadnadearriba"
    token:
      secure: "VqD43Z3bh95AJs7pKk9IfHYffiDtMrEu+C3BqDnfAeiAtKhz12+nxtcif27xnRnaYcJkqMoVB3lk5E6paaZmVEjjLgTkzIbrH4BNO0ckNkbrxILqwamgA56/cYHPA084E/zGf7X6pUAEIcD1xuJaBEioaNeRNKcq4+CDT8ldvizV8jyepNRtfKzRIQ+fgchXcO4aGBiGRxjdblza3dOAKstdehcDXLMYd0hQh+woPye3UO9fvgku+gTv3RSy/qkcxC7cHTVhGrlMGCqvdf0ms2ODqnGTWsYT2+totibx1fbgdnV35Wvo2NXVcUP9vJd9rq3oU7gd5621HAY92DXpo6W2SulqUsDIO8xQeNvj67wcr5/JOz2ZJSVIQw3V8tWIMMiZ37WSpUgyAXOt5x0Iua3MFR3n//alwV9x7qQMBR2x25sK/BGanwwv8dZZeo0+XtiuEwFHiRHo4VNQLRSf1M4TiwpLLGDOFN+kJkCa5unauSa/JacRExXcl85rBIYkko1hxz8ujexywSg0BjvukxT7DyLe4H3ZteEzZSKoBQhlmCVVCo+xgrEnww83hSkZBOt2X0jvPe1/vDsWIe4+CqADk3SaUtxAIIiCORF1CsR3mCT8i8Z8XhoJqfr9lkAzy0TGdxa0FFcn51EEhOiVQFibnbWz/Bgavngflt49kzY="

env:
  secure: "zHGhwF1Od9Bo22o/l3YewuYhiT7NAWcmsdDnNTaDH+Bc+PpiSbIi+P3hBi73HFW9ait4kUGxFbXJKDmRx1u8p/rvZSNHSoOQMEmW56v5lf6Xx/goEr1Z4amz8kL+8tPYeXV7zABHg8EO+obLNGLL5zpJDW/Qv9WGi0tdH6iFKpzh0TNyJwS+RcdAMDVbLytGmN3dzSEv+P6xTopzvwIhL4VW/ZIwqfJ6TGphhJg3QA8cETkfRo/pEIBWKdxjtp4fA/AdaXCGAu09JaBCP40y0rOaM0/C1T2L7WLLgkEvteqSa1S4irvhTX/sXYEYnx7s1BPYJqbZBrChFJWSQISjgfnr9g4U1PVwvFBEyfVgk3iUImQipGr5wN0MJC9wfmeBY6prHNw6OmeihM/C5HkoHjDGfNvORRT/M/VmvQSf43xLBtq3ZUy/a2e6OHkWUdN9+HsEIFmy+9cwpoMVG9KHfl5z9uQNc3gxIXZHzYLcgr1+ZgHuuwUPEh+6m1a0DTgYfSAPXj1snEdAHZMqbAOL0LEqZikTtZMpqsmk/x+MukVh3ZSTDvF3FQLsgIB3napvh3Zpjs9YJcvh2Z7qdQHrwa7JzWJ3r8oJVWDr8mbaSrzGiTv/iAA8cLGH94S41aC2FfOzRWpe3Addx6rch5bFuW/9JKjnU12G326M4n4hXg4="

before_install:
  - chmod +x mvnw

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ariadnadearriba_API-Sentiment-Analysis -Dsonar.branch.name=staging

after_success:
  - chmod a+x automerge
  - BRANCHES_TO_MERGE_REGEX='staging' BRANCH_TO_MERGE_INTO=development GITHUB_REPO=ariadnadearriba/API-Sentiment-Analysis ./automerge
