dist: xenial

language: java

jdk:
  - openjdk8

branches:
  only:
    - staging

#addons:
#  sonarcloud:
#    organization: "ariadnadearriba"
#    token:
#      secure: ""
env:
  secure: "8mOuFW5kfQBI6Lx13hYoWTjE4N791mn6"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ariadnadearriba_API-Sentiment-Analysis -Dsonar.branch.name=staging

after_success:
  - chmod a+x automerge
  - BRANCHES_TO_MERGE_REGEX='staging' BRANCH_TO_MERGE_INTO=development GITHUB_REPO=aridearriba/API-Sentiment-Analysis ./automerge