dist: xenial

language: java

jdk:
  - openjdk8

branches:
  only:
    - staging

addons:
  sonarcloud:
    organization: "ariadnadearriba"
    token:
      secure: "enzEPHpbvbfmWXk5wyaBMSQjpWjiM5I1bKrMBiId7vpmjtka2QIyvep7TmKBBXYV+d2JH0aXJ8ccIV6jd4n+uBxic88G9uG7PaUrPxj5ywQITIWLIg3SRVYfTh6GrjKZnfp0jJ4KoVZC/VCyd1uruTRnTGqs9wu3aRQat/N/UpMiSOI/xjqgZ7zO8O+fGJ8dUPHXUJpoQ5XtTF78QfaKMsSxNvQMkwKat72mUrMueXvtYCpySCchxas1sW27swCAngo8Zhp4lIDAP8YPp+Ce/pUup3UwyDQN9lNIRLte34WrMnIvszKp93zCiTqwDJSRIJ+hQZIw68/pJy2fdWwl05dw5e1iQ8GGQPRmcFz7nWrRrVX7rzVJ3qDXJXm4Er0bwBzkisHIXnOAlyWRDK0ZGjiEA/GgxbwvpGo2GFsgQNq/OLNHcBwePwrWISjOvYO2YMfIKMpz6Wcq/nJ8W/062arp5O8uf4YxrTveas/3yCgq2IdznaLdq3PL7Xxmjcy2hZ3V3TezHgtiJhRh1eNjcwExrVkjCh/j4b5LlFr5lM5+SWMW8F3uT6lVupep4ihMVj/yrBnKymdm21i7g+nM//isaJypyyhNGyrltLzeIZ3dQJ+WXWTzQgWN3Dphm9JROqYMAjklSDt4dcrxB4sexbt8pab2M1/kq9qSw91I5LQ="

env:
  secure: "GMlUnNtAHPrfG7J1X9JkKwBbSIYunWRfo212Ak7mccmywdA8rkUxU9VbCJRCAXwh0BBHPY/AKDVE1r0kRQC/KO4q54xC5zCO1dB02i7nF3NpcWpD3cfVJ7SfOaYtf9w+A2wTJtYjh5opK9wlRQI9JpQUuUBK05JUjOmkzGroEl/daVMAKBcIt41RLy/bMhnHH8nfTahlpB9AjH1dap5R4jyAU/V1d2ufm0nGI3n9K+pflsyoKvuNLtFarYxo/kURWTX3Pij3v3X39fK40Lr/glladnCaMTFf0Al9zNzsfvxD5Qf1SZiotPx2kdr3ygUnnS9Hv4VrELtd/7o83VP4SbAVQS0Ks7KiwvULN148olX439x99Tb5dLQzhrC6u3p6VJOKBwk5Vt/0MKCUQvE2G6Hb9b/WrOWRPHaKdg0nTiOcnHDEwZmWSRYYRDBC0r1rz9ykDb77gZZtdS/W0nLJ9dVVP8Jmw+e6zBMEQXUIwCWnZCNQxxhv6+D+zbRD8qi/7chtJhjv7pf4Qi9y8nWmtutE+ZvNsRC0zl4bR4dUx7DLFDf3tp0Q7h5N7rQB0Ej8uzqfYqvLrsBOnn1J7HX29tA8nJjKqKoepaz6rVeviJ5zM1Z+nEK6rHtchyIlHofXcjiSTQzJ9BQBqzxi1B6yo8qbCL8+Mog5cWAoyr4vAno"

before_install:
  - chmod +x mvnw

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ariadnadearriba_API-Sentiment-Analysis -Dsonar.branch.name=staging

after_success:
  - chmod a+x automerge
  - BRANCHES_TO_MERGE_REGEX='staging' BRANCH_TO_MERGE_INTO=development GITHUB_REPO=aridearriba/API-Sentiment-Analysis ./automerge

