dist: xenial
language: java
jdk:
- openjdk12
branches:
  only:
  - staging
addons:
  sonarcloud:
    organization: ariadnadearriba
    token:
      secure: enzEPHpbvbfmWXk5wyaBMSQjpWjiM5I1bKrMBiId7vpmjtka2QIyvep7TmKBBXYV+d2JH0aXJ8ccIV6jd4n+uBxic88G9uG7PaUrPxj5ywQITIWLIg3SRVYfTh6GrjKZnfp0jJ4KoVZC/VCyd1uruTRnTGqs9wu3aRQat/N/UpMiSOI/xjqgZ7zO8O+fGJ8dUPHXUJpoQ5XtTF78QfaKMsSxNvQMkwKat72mUrMueXvtYCpySCchxas1sW27swCAngo8Zhp4lIDAP8YPp+Ce/pUup3UwyDQN9lNIRLte34WrMnIvszKp93zCiTqwDJSRIJ+hQZIw68/pJy2fdWwl05dw5e1iQ8GGQPRmcFz7nWrRrVX7rzVJ3qDXJXm4Er0bwBzkisHIXnOAlyWRDK0ZGjiEA/GgxbwvpGo2GFsgQNq/OLNHcBwePwrWISjOvYO2YMfIKMpz6Wcq/nJ8W/062arp5O8uf4YxrTveas/3yCgq2IdznaLdq3PL7Xxmjcy2hZ3V3TezHgtiJhRh1eNjcwExrVkjCh/j4b5LlFr5lM5+SWMW8F3uT6lVupep4ihMVj/yrBnKymdm21i7g+nM//isaJypyyhNGyrltLzeIZ3dQJ+WXWTzQgWN3Dphm9JROqYMAjklSDt4dcrxB4sexbt8pab2M1/kq9qSw91I5LQ=
env:
  secure: zHGhwF1Od9Bo22o/l3YewuYhiT7NAWcmsdDnNTaDH+Bc+PpiSbIi+P3hBi73HFW9ait4kUGxFbXJKDmRx1u8p/rvZSNHSoOQMEmW56v5lf6Xx/goEr1Z4amz8kL+8tPYeXV7zABHg8EO+obLNGLL5zpJDW/Qv9WGi0tdH6iFKpzh0TNyJwS+RcdAMDVbLytGmN3dzSEv+P6xTopzvwIhL4VW/ZIwqfJ6TGphhJg3QA8cETkfRo/pEIBWKdxjtp4fA/AdaXCGAu09JaBCP40y0rOaM0/C1T2L7WLLgkEvteqSa1S4irvhTX/sXYEYnx7s1BPYJqbZBrChFJWSQISjgfnr9g4U1PVwvFBEyfVgk3iUImQipGr5wN0MJC9wfmeBY6prHNw6OmeihM/C5HkoHjDGfNvORRT/M/VmvQSf43xLBtq3ZUy/a2e6OHkWUdN9+HsEIFmy+9cwpoMVG9KHfl5z9uQNc3gxIXZHzYLcgr1+ZgHuuwUPEh+6m1a0DTgYfSAPXj1snEdAHZMqbAOL0LEqZikTtZMpqsmk/x+MukVh3ZSTDvF3FQLsgIB3napvh3Zpjs9YJcvh2Z7qdQHrwa7JzWJ3r8oJVWDr8mbaSrzGiTv/iAA8cLGH94S41aC2FfOzRWpe3Addx6rch5bFuW/9JKjnU12G326M4n4hXg4=

before_install:
  - chmod +x mvnw
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ariadnadearriba_API-Sentiment-Analysis -Dsonar.branch.name=staging
after_success:
  - chmod a+x automerge
  - BRANCHES_TO_MERGE_REGEX='staging' BRANCH_TO_MERGE_INTO=development GITHUB_REPO=ariadnadearriba/API-Sentiment-Analysis ./automerge
