dist: xenial
language: java
jdk:
- openjdk12
branches:
  only:
  - staging
addons:
  sonarcloud:
    organization: ariadnadearriba
    token:
      secure: cjiOV82InfBC7R7JuVo9jUueTe2/yzOW5ahhrvG3hwhMZmsXm37X1TV3K0BLbxsrWn/es8DedV8lOVClsX7weVJEb+6+CpYBGVImOuCSCbTYgGMQjpKcoxTsdwoJM3yyXPZO8ERFek2+YoTkSrrbOiDnHAA0uYOfxfADa0J0Giq3665rOODwdoAJrUDlxw4HYpe+u2iM5CQMsEqsXJbZRjH8QzR5dI6WlFRluzVR/8ZXzfvh/JXUlD+sgkUNAN+h5TzVfJD2xYh/zVggMqX9lD395jOGcLauXfSQPSNY7q79l9oPohVbIbDBrFaRLxR0XGMOsSH3Qt+I5b4gQM0dw+cIL+ZFPDQxrHL4KYrcUnqmU9XEJvD86XGz7XrG9uc5u35/lP05mlxqh6ADTtNYv99s+Rt9yok4Y/ngNzGry05l7d1s/JsrDFIMs8zueSV5keyPBAK7jm2mKwNEDw1wj/PLIuL9RXr/AtZVLVs3aWP6/AaELIT41gPJyVqJ/KjrE30yaOxDB6T719XP4Vo6u6htt6vZw0fTzCkS/V3QNJ07F6jpby9myb6Vy6Uq/iWBTto04RM8KgHT5GriS0l0VTAM7SsEnnhs/5u+V8BWy16VqX8QLR0Kjj/oMCeu3X3mpsjK5mF6JAhuhrYLDiO0qbjbueJ9y0Id+frlCzP+5fk=

env:
  secure: zHGhwF1Od9Bo22o/l3YewuYhiT7NAWcmsdDnNTaDH+Bc+PpiSbIi+P3hBi73HFW9ait4kUGxFbXJKDmRx1u8p/rvZSNHSoOQMEmW56v5lf6Xx/goEr1Z4amz8kL+8tPYeXV7zABHg8EO+obLNGLL5zpJDW/Qv9WGi0tdH6iFKpzh0TNyJwS+RcdAMDVbLytGmN3dzSEv+P6xTopzvwIhL4VW/ZIwqfJ6TGphhJg3QA8cETkfRo/pEIBWKdxjtp4fA/AdaXCGAu09JaBCP40y0rOaM0/C1T2L7WLLgkEvteqSa1S4irvhTX/sXYEYnx7s1BPYJqbZBrChFJWSQISjgfnr9g4U1PVwvFBEyfVgk3iUImQipGr5wN0MJC9wfmeBY6prHNw6OmeihM/C5HkoHjDGfNvORRT/M/VmvQSf43xLBtq3ZUy/a2e6OHkWUdN9+HsEIFmy+9cwpoMVG9KHfl5z9uQNc3gxIXZHzYLcgr1+ZgHuuwUPEh+6m1a0DTgYfSAPXj1snEdAHZMqbAOL0LEqZikTtZMpqsmk/x+MukVh3ZSTDvF3FQLsgIB3napvh3Zpjs9YJcvh2Z7qdQHrwa7JzWJ3r8oJVWDr8mbaSrzGiTv/iAA8cLGH94S41aC2FfOzRWpe3Addx6rch5bFuW/9JKjnU12G326M4n4hXg4=

before_install:
  - chmod +x mvnw
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ariadnadearriba_API-Sentiment-Analysis -Dsonar.branch.name=staging
after_success:
  - chmod a+x automerge
  - BRANCHES_TO_MERGE_REGEX='staging' BRANCH_TO_MERGE_INTO=development GITHUB_REPO=ariadnadearriba/API-Sentiment-Analysis ./automerge
