dist: xenial
language: java
jdk:
- openjdk12
branches:
  only:
  - staging
addons:
  sonarcloud:
    organization: ariadnadearriba
    token:
      secure: 6LvuLyhmt+S7ZnOXpKbmzBpRBJiNnbRBoCLd5ecNQn5NVRbhg6Yuy/KNztzsNFsTLcDvdK+15BgkjuXuZzs3gSoeMWX+jhM2GlXToAhtFq6IsCJuHduf3C3DF/BiIO8atIwiVrAldmWcRdt7QwRS15ym+evFsOAjDtAlUMDhhTR7VoIwzS987iRHGj1BbZc7OFD3uU1ye0EyaN5YLeXOTJd0M8oreuOAZXuNuSLIeKa7QYRN/4qT0tPSh4WEHJMoxs0dv2MNk73xu4rvV8yKcVQx4tT7eV1cGH4PXUH9Ge9pr6oAETcoRPyCz17yXWV+lT6Amc8wvHMqrVaTqkiKrOyxmL/gXIy5j8d51sbDxx0cyMuTpW7edMeCq4l/bLHp53ik4KbLpZCV0PwAGalZoRE8MImjjocQkfXP2gCbzoQaNpFcAH2MMQ3hPJMvToG2LuOsTGl+EaTzcbg+3EmNl4EkTJoGK0gL2G0xeVQHuQ/V/YQEDDjTfJrlZt2JLKI0NjyK6NPt96FTvoZoQNVDdJnMNVKGJhXrDVbVtRncdQ6z8VwjNxs/CygLhAIbzDx4OFFEhdsonvszeVp4m+jjD2JAPoT9Qwd3y4xwChVng1yk2xTNTyQSOr6B4UN5QB6fZlxfH3LEJObl7nOO+j/NHQNYqoHVY8mSeTjvptEZEmU=

env:
  secure: zHGhwF1Od9Bo22o/l3YewuYhiT7NAWcmsdDnNTaDH+Bc+PpiSbIi+P3hBi73HFW9ait4kUGxFbXJKDmRx1u8p/rvZSNHSoOQMEmW56v5lf6Xx/goEr1Z4amz8kL+8tPYeXV7zABHg8EO+obLNGLL5zpJDW/Qv9WGi0tdH6iFKpzh0TNyJwS+RcdAMDVbLytGmN3dzSEv+P6xTopzvwIhL4VW/ZIwqfJ6TGphhJg3QA8cETkfRo/pEIBWKdxjtp4fA/AdaXCGAu09JaBCP40y0rOaM0/C1T2L7WLLgkEvteqSa1S4irvhTX/sXYEYnx7s1BPYJqbZBrChFJWSQISjgfnr9g4U1PVwvFBEyfVgk3iUImQipGr5wN0MJC9wfmeBY6prHNw6OmeihM/C5HkoHjDGfNvORRT/M/VmvQSf43xLBtq3ZUy/a2e6OHkWUdN9+HsEIFmy+9cwpoMVG9KHfl5z9uQNc3gxIXZHzYLcgr1+ZgHuuwUPEh+6m1a0DTgYfSAPXj1snEdAHZMqbAOL0LEqZikTtZMpqsmk/x+MukVh3ZSTDvF3FQLsgIB3napvh3Zpjs9YJcvh2Z7qdQHrwa7JzWJ3r8oJVWDr8mbaSrzGiTv/iAA8cLGH94S41aC2FfOzRWpe3Addx6rch5bFuW/9JKjnU12G326M4n4hXg4=

before_install:
  - chmod +x mvnw
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ariadnadearriba_API-Sentiment-Analysis -Dsonar.branch.name=staging
after_success:
  - chmod a+x automerge
  - BRANCHES_TO_MERGE_REGEX='staging' BRANCH_TO_MERGE_INTO=development GITHUB_REPO=ariadnadearriba/API-Sentiment-Analysis ./automerge
